#define FOSC	24				//定义晶振频率
#define	INIT_TH0 0x3C			//定时器T0初始值
#define	INIT_TL0 0xB0
#define	TMOD_T00 0x00			//定义T0为方式0，GATE=0，C/T=0,13位计数器
#define	TMOD_T01 0x01			//定义T0为方式1，GATE=0，C/T=0,16位计数器
#define	TMOD_T02 0x02			//定义T0为方式2，GATE=0,C/T=0,自动装入8位计数器
#define	TMOD_T03 0x03			//定义T0为方式3，GATE=0,C/T=0，定时器0分成两个8位计数器，定时器1停止计数

/*缩定定义*/

#define uchar unsigned char
#define	uint unsigned int

/*P1口位定义*/


/*P2 BIT Define*/


/*P3 bit define*/